
name: 🐞 Bug report
description: Report an issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: How to trigger it, it would be better to have screenshots 怎么触发，有截图更好
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true

  - type: dropdown
    id: OS
    attributes:
      label: OS/系统
      options:
        - Windows
        - Mac
        - Ubuntu
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser/浏览器
      options:
        - Chrome
        - Edge
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: 是否关闭其他插件/Have you close other extensions?
        - label: 是否禁用自定义js/Have you disable custom js file?