name: Feature request/功能请求
about: Feature request/功能请求
title: ''
labels: enhancement
assignees: ''
body:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you know something about the project.
      options:
        - label: DO NOT SUPPORT FIREFOX OR CORE WITH FIREFOX
    validations:
      required: true 
  - type: textarea
    id: description
    attributes:
      label: Description 描述
    validations:
      required: true


