name: Help wanted/需要帮助
description: Help wanted/需要帮助
labels: help wanted
body:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you know something about the project.
      options:
        - label: DO NOT SUPPORT FIREFOX OR CORE WITH FIREFOX
          required: true 
  - type: textarea
    id: description
    attributes:
      label: Description 描述
    validations:
      required: true


